apiVersion: v1
kind: Service
metadata:
  name: hello-server-service
  labels:
    app: hello-server
spec:
  selector:
    app: hello-server
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: hello-server-nodeport
  labels:
    app: hello-server
spec:
  selector:
    app: hello-server
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30080
    protocol: TCP
  type: NodePort

